name: Multi-job workflow

on:
  push:
    branches:
      - main
      - feature/pr-trigger-check  # 必要に応じてブランチ名追加

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job1 step
        run: echo "job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job2 step
        run: echo "job2"