name: Needs-practice workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: First job step
        run: echo "first job"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Second job step
        run: echo "second job"